"""Added confirmed table to the user databases

Revision ID: 12a14fc7b734
Revises: 772e4035500
Create Date: 2015-03-24 08:22:07.922000

"""

# revision identifiers, used by Alembic.
revision = '12a14fc7b734'
down_revision = '772e4035500'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
