"""Resend account confirmation email & add database commit

Revision ID: 1cde516d217
Revises: 12a14fc7b734
Create Date: 2015-03-25 15:55:00.230000

"""

# revision identifiers, used by Alembic.
revision = '1cde516d217'
down_revision = '12a14fc7b734'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
