"""initial migration

Revision ID: 42fd6cc3e730
Revises: None
Create Date: 2015-03-23 04:41:03.778000

"""

# revision identifiers, used by Alembic.
revision = '42fd6cc3e730'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
