"""Created Email Table For User

Revision ID: 772e4035500
Revises: 42fd6cc3e730
Create Date: 2015-03-24 03:41:03.147000

"""

# revision identifiers, used by Alembic.
revision = '772e4035500'
down_revision = '42fd6cc3e730'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
